using FluentMigrator.Builders.Create.Table;
using O24OpenAPI.Data.Mapping.Builders;

namespace O24OpenAPI.Web.CMS.Migrations.Builder;

public class S_TRANSACTIONFIELDBuilder : O24OpenAPIEntityBuilder<S_TRANSACTIONFIELD>
{
    public override void MapEntity(CreateTableExpressionBuilder table)
    {
        table
            .WithColumn(nameof(S_TRANSACTIONFIELD.TransactionCode))
            .AsString(50)
            .NotNullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.TransactionField))
            .AsString(25)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.FiledType))
            .AsString(3)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Caption))
            .AsString(4000)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.MaxLength))
            .AsInt32()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.MinWidth))
            .AsInt32()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Height))
            .AsInt32()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.FunctionDecimal))
            .AsInt32()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Mask))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Format))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Enable))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Visible))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Editable))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.IsRequire))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Clear))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Israte))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Tag))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Index))
            .AsInt32()
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Limit))
            .AsString(1000)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.InOut))
            .AsString(10)
            .Nullable()
            .WithColumn(nameof(S_TRANSACTIONFIELD.Map))
            .AsString(2)
            .Nullable();
    }
}
