using FluentMigrator.Builders.Create.Table;
using O24OpenAPI.Data.Mapping.Builders;

namespace O24OpenAPI.Web.CMS.Migrations;

/// <summary>
/// S_USERPORTAL
/// </summary>
public class UserPortalBuilder : O24OpenAPIEntityBuilder<S_USERPORTAL>
{
    public override void MapEntity(CreateTableExpressionBuilder table)
    {
        table
            .WithColumn(nameof(S_USERPORTAL.UserName))
            .AsString(50)
            .NotNullable()
            .WithColumn(nameof(S_USERPORTAL.UserCode))
            .AsString(50)
            .NotNullable()
            .WithColumn(nameof(S_USERPORTAL.FirstName))
            .AsString(255)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.MiddleName))
            .AsString(255)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.LastName))
            .AsString(255)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Gender))
            .AsInt32()
            .WithDefaultValue(0)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Birthday))
            .AsDateTime2()
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Address))
            .AsString(500)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Email))
            .AsString(255)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Phone))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Status))
            .AsString(10)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.UserCreated))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.DateCreated))
            .AsDateTime2()
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.LastLoginTime))
            .AsDateTime2()
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.UserModified))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.DateModified))
            .AsDateTime2()
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.IsLogin))
            .AsBoolean()
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.ExpireTime))
            .AsDateTime2()
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.BranchID))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.DepartmentCode))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.UserLevel))
            .AsInt32()
            .WithDefaultValue(0)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.UserType))
            .AsString(50)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.IsShow))
            .AsString(10)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.PolicyID))
            .AsInt32()
            .WithDefaultValue(0)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.UUID))
            .AsString(255)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.Failnumber))
            .AsInt32()
            .WithDefaultValue(0)
            .Nullable()
            .WithColumn(nameof(S_USERPORTAL.IsSuperAdmin))
            .AsBoolean()
            .WithDefaultValue(false)
            .Nullable();
    }
}
