USE o24cth
GO
IF OBJECT_ID('dbo.REPORT_BRANCH', 'P ') IS NOT NULL DROP PROCEDURE dbo.REPORT_BRANCH;
GO
CREATE PROCEDURE [dbo].[REPORT_BRANCH]
AS
BEGIN
  CREATE TABLE #tranapp(
		[BRANCHCODE] VARCHAR(50) NOT NULL,
		[BRANCHNAME] NVARCHAR(1000) NOT NULL
)
INSERT INTO #tranapp(BRANCHCODE,BRANCHNAME)
	VALUES('',N'All')
	INSERT INTO #tranapp(BRANCHCODE,BRANCHNAME)
	SELECT BranchID,BranchID+ ' - ' + BranchName from D_BRANCH ORDER BY BranchID

SELECT * FROM #tranapp

DROP TABLE #tranapp
END;
GO