using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace O24OpenAPI.Generator;

[Generator]
public class LearnApiSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<MethodInfo?> methodsWithAttribute = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax method && method.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetMethodInfo(ctx)
            )
            .Where(static m => m is not null);

        IncrementalValueProvider<(
            Compilation Left,
            ImmutableArray<MethodInfo?> Right
        )> compilationAndMethods = context.CompilationProvider.Combine(
            methodsWithAttribute.Collect()
        );

        context.RegisterSourceOutput(
            compilationAndMethods,
            static (spc, source) => Execute(source.Left, source.Right!, spc)
        );
    }

    private static MethodInfo? GetMethodInfo(GeneratorSyntaxContext context)
    {
        MethodDeclarationSyntax methodSyntax = (MethodDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(methodSyntax) is not IMethodSymbol methodSymbol)
            return null;

        AttributeData? learnApiAttribute = methodSymbol
            .GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.Name == "LearnApiAttribute"
                && a.AttributeClass?.ContainingNamespace?.ToDisplayString()
                    == "O24OpenAPI.Framework.Attributes"
            );

        if (learnApiAttribute is null)
            return null;

        string? learnApiId = learnApiAttribute
            .ConstructorArguments.FirstOrDefault()
            .Value?.ToString();
        if (string.IsNullOrEmpty(learnApiId))
            return null;

        ImmutableArray<IParameterSymbol> parameters = methodSymbol.Parameters;
        if (parameters.Length == 0)
            return null;

        ITypeSymbol requestType = parameters[0].Type;
        string requestTypeFullName = requestType.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );

        bool isCommand = ImplementsInterface(requestType, "ICommand");
        bool isQuery = ImplementsInterface(requestType, "IQuery");

        return new MethodInfo(learnApiId!, requestTypeFullName, isCommand, isQuery);
    }

    private static bool ImplementsInterface(ITypeSymbol typeSymbol, string interfaceName)
    {
        return typeSymbol.AllInterfaces.Any(i => i.Name == interfaceName);
    }

    private static void Execute(
        Compilation compilation,
        IEnumerable<MethodInfo> methods,
        SourceProductionContext context
    )
    {
        if (!methods.Any())
            return;

        string source = GenerateSource(methods);
        context.AddSource("LearnApiHandlers.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(IEnumerable<MethodInfo> methods)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using LinKit.Core.Cqrs;");
        sb.AppendLine("using LinKit.Json.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace O24OpenAPI.CMS.API");
        sb.AppendLine("{");
        sb.AppendLine("    internal static partial class LearnApiHandlers");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        private static readonly Dictionary<string, Func<object, IMediator, CancellationToken, Task<object>>> _handlers ="
        );
        sb.AppendLine("            new(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("            {");

        List<MethodInfo> methodList = methods.ToList();
        for (int i = 0; i < methodList.Count; i++)
        {
            MethodInfo method = methodList[i];
            string mediatorMethod = method.IsQuery ? "QueryAsync" : "SendAsync";

            sb.AppendLine(
                $"                [\"{method.LearnApiId}\"] = static async (request, mediator, token) =>"
            );
            sb.AppendLine("                {");
            sb.AppendLine(
                $"                    var command = request.ToJson().FromJson<{method.RequestType}>() ?? new {method.RequestType}();"
            );
            sb.AppendLine(
                $"                    return await mediator.{mediatorMethod}(command, token);"
            );
            sb.Append("                }");

            if (i < methodList.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("        public static async Task<object> HandleAsync(");
        sb.AppendLine("            string learnApiId,");
        sb.AppendLine("            object request,");
        sb.AppendLine("            IMediator mediator,");
        sb.AppendLine("            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_handlers.TryGetValue(learnApiId, out var handler))");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                return await handler(request, mediator, cancellationToken);"
        );
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine(
            "            throw new InvalidOperationException($\"No handler found for LearnApiId: {learnApiId}\");"
        );
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(
            "        public static bool TryGetHandler(string learnApiId, out Func<object, IMediator, CancellationToken, Task<object>>? handler)"
        );
        sb.AppendLine("        {");
        sb.AppendLine("            return _handlers.TryGetValue(learnApiId, out handler);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record MethodInfo(string LearnApiId, string RequestType, bool IsCommand, bool IsQuery);
}
