using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace O24OpenAPI.Generators;

[Generator]
public class GrpcMediatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax,
                transform: (ctx, _) => GetSemanticTargetForGeneration(ctx)
            )
            .Where(m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(
            classDeclarations.Collect()
        );

        context.RegisterSourceOutput(
            compilationAndClasses,
            (spc, source) => Execute(source.Left, source.Right, spc)
        );
    }

    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(
        GeneratorSyntaxContext context
    )
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        if (symbol is INamedTypeSymbol classSymbol)
        {
            var baseType = classSymbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "BaseGrpcClientService")
                    return classDeclaration;
                baseType = baseType.BaseType;
            }
        }
        return null;
    }

    private void Execute(
        Compilation compilation,
        System.Collections.Immutable.ImmutableArray<ClassDeclarationSyntax?> classes,
        SourceProductionContext context
    )
    {
        if (classes.IsDefaultOrEmpty)
            return;

        var servicesToGenerate = new List<ServiceMetadata>();

        foreach (var classDecl in classes.Distinct())
        {
            var model = compilation.GetSemanticModel(classDecl!.SyntaxTree);
            var symbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol == null)
                continue;

            var serviceMetadata = new ServiceMetadata
            {
                ClassName = symbol.Name,
                // Lấy Interface đầu tiên hoặc mặc định I + ClassName
                InterfaceName = symbol.Interfaces.FirstOrDefault()?.Name ?? $"I{symbol.Name}",
                Namespace = symbol.ContainingNamespace.ToDisplayString(),
                Methods = new List<MethodMetadata>(),
            };

            var methods = symbol
                .GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m =>
                    m.DeclaredAccessibility == Accessibility.Public
                    && m.MethodKind == MethodKind.Ordinary
                );

            foreach (var method in methods)
            {
                string responseType = "Unit";
                if (method.ReturnType is INamedTypeSymbol returnType)
                {
                    if (
                        returnType.IsGenericType
                        && (returnType.Name == "Task" || returnType.Name == "ValueTask")
                    )
                    {
                        responseType = returnType.TypeArguments[0].ToDisplayString();
                    }
                }

                serviceMetadata.Methods.Add(
                    new MethodMetadata
                    {
                        MethodName = method.Name,
                        ResponseType = responseType,
                        Parameters = method
                            .Parameters.Select(p => new ParameterMetadata
                            {
                                Name = p.Name,
                                Type = p.Type.ToDisplayString(),
                            })
                            .ToList(),
                    }
                );
            }
            servicesToGenerate.Add(serviceMetadata);
        }

        GenerateCode(context, servicesToGenerate);
    }

    private void GenerateCode(SourceProductionContext context, List<ServiceMetadata> services)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using LinKit.Core.Cqrs;");

        // --- LẤY VÀ THÊM CÁC NAMESPACE CỦA GRPC CLIENTS ---
        var distinctNamespaces = services.Select(s => s.Namespace).Distinct().OrderBy(n => n);
        foreach (var ns in distinctNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();

        // 1. Generate Commands
        sb.AppendLine("namespace O24OpenAPI.GrpcClient.Generated");
        sb.AppendLine("{");
        foreach (var service in services)
        {
            foreach (var method in service.Methods)
            {
                var props = string.Join(
                    ", ",
                    method.Parameters.Select(p => $"{p.Type} {Capitalize(p.Name)}")
                );
                sb.AppendLine(
                    $"    public record {service.ClassName}{method.MethodName}Command({props}) : ICommand<{method.ResponseType}>;"
                );
            }
        }
        sb.AppendLine("}");

        // 2. Generate GrpcMediator
        sb.AppendLine("\nnamespace O24OpenAPI.Generated.Mediator");
        sb.AppendLine("{");
        sb.AppendLine("    public class GrpcMediator : IMediator");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine(
            "        public GrpcMediator(IServiceProvider serviceProvider) => _serviceProvider = serviceProvider;"
        );

        // SendAsync<TResponse>
        sb.AppendLine(
            "\n        public async Task<TResponse> SendAsync<TResponse>(ICommand<TResponse> command, CancellationToken ct = default)"
        );
        sb.AppendLine("        {");
        sb.AppendLine("            return command switch");
        sb.AppendLine("            {");
        foreach (var service in services)
        {
            foreach (var method in service.Methods)
            {
                var cmdType =
                    $"O24OpenAPI.GrpcClient.Generated.{service.ClassName}{method.MethodName}Command";
                var args = string.Join(
                    ", ",
                    method.Parameters.Select(p => $"c.{Capitalize(p.Name)}")
                );

                // Sử dụng InterfaceName đã tìm được để gọi Service
                sb.AppendLine(
                    $"                {cmdType} c => (TResponse)(object)await _serviceProvider.GetRequiredService<{service.InterfaceName}>().{method.MethodName}({args}),"
                );
            }
        }
        sb.AppendLine(
            "                _ => throw new NotImplementedException($\"Command {command.GetType().Name} not registered in GrpcMediator.\")"
        );
        sb.AppendLine("            };");
        sb.AppendLine("        }");

        sb.AppendLine(
            "\n        public async Task SendAsync(ICommand command, CancellationToken ct = default) => throw new NotImplementedException();"
        );
        sb.AppendLine(
            "\n        public async Task<TResponse> QueryAsync<TResponse>(IQuery<TResponse> query, CancellationToken ct = default) => throw new NotImplementedException();"
        );
        sb.AppendLine("    }");

        // 3. DI Registration
        sb.AppendLine("\n    public static class GrpcMediatorExtensions");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        public static IServiceCollection AddGrpcMediator(this IServiceCollection services)"
        );
        sb.AppendLine("        {");
        sb.AppendLine("            services.AddKeyedScoped<IMediator, GrpcMediator>(\"grpc\");");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GrpcMediator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

        var sb1 = new StringBuilder();
        sb1.AppendLine("// <auto-generated />");
        sb1.AppendLine("global using O24OpenAPI.GrpcClient.Generated;");
        context.AddSource("GrpcClient.GlobalUsing.g.cs", SourceText.From(sb1.ToString(), Encoding.UTF8));
    }

    private string Capitalize(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1);

    private class ServiceMetadata
    {
        public string ClassName { get; set; }
        public string InterfaceName { get; set; }
        public string Namespace { get; set; }
        public List<MethodMetadata> Methods { get; set; }
    }

    private class MethodMetadata
    {
        public string MethodName { get; set; }
        public string ResponseType { get; set; }
        public List<ParameterMetadata> Parameters { get; set; }
    }

    private class ParameterMetadata
    {
        public string Name { get; set; }
        public string Type { get; set; }
    }
}
