// <auto-generated>
// Generated to match CTH/NCH repository pattern.
// </auto-generated>

using LinqToDB;
using O24OpenAPI.ACT.Domain.AggregatesModel.CommonAggregate;
using O24OpenAPI.Core.Caching;
using O24OpenAPI.Data;

namespace O24OpenAPI.ACT.Infrastructure.Repositories;

public class BranchRepository(
    IO24OpenAPIDataProvider dataProvider,
    IStaticCacheManager staticCacheManager
) : EntityRepository<Branch>(dataProvider, staticCacheManager), IBranchRepository
{
    public Task<Branch?> GetByCodeAsync(string branchCode)
        => Table.FirstOrDefaultAsync(x => x.BranchCode == branchCode);
}
