// <auto-generated>
// Generated to match CTH/NCH repository pattern.
// </auto-generated>

using LinqToDB;
using O24OpenAPI.ACT.Domain.AggregatesModel.AccountAggregate;
using O24OpenAPI.ACT.Domain;
using O24OpenAPI.Core.Caching;
using O24OpenAPI.Data;
using O24OpenAPI.Data.Extensions;

namespace O24OpenAPI.ACT.Infrastructure.Repositories;

public class AccountBalanceRepository(
    IO24OpenAPIDataProvider dataProvider,
    IStaticCacheManager staticCacheManager
) : EntityRepository<AccountBalance>(dataProvider, staticCacheManager), IAccountBalanceRepository
{
    public Task<AccountBalance?> GetByAccountNumberAsync(string accountNumber)
        => Table.FirstOrDefaultAsync(x => x.AccountNumber == accountNumber);

    public virtual async Task<AccountBalance> GetByAccountNumber(string accountNumber)
    {
        
        var accountBalance = await 
            Table.Where(c => c.AccountNumber == accountNumber)
            .FirstOrDefaultAsync();
        if (accountBalance is null)
        {
            accountBalance = new AccountBalance { AccountNumber = accountNumber };
            await accountBalance.Insert();
        }
        return accountBalance;

    }
}
