// <auto-generated>
// Generated to match CTH/NCH repository pattern.
// </auto-generated>

using LinqToDB;
using O24OpenAPI.ACT.Domain.AggregatesModel.AccountAggregate;
using O24OpenAPI.ACT.Domain;
using O24OpenAPI.Core.Caching;
using O24OpenAPI.Data;

namespace O24OpenAPI.ACT.Infrastructure.Repositories;

public class AccountChartRepository(
    IO24OpenAPIDataProvider dataProvider,
    IStaticCacheManager staticCacheManager
) : EntityRepository<AccountChart>(dataProvider, staticCacheManager), IAccountChartRepository
{
    public Task<AccountChart?> GetByAccountNumberAsync(string accountNumber)
        => Table.FirstOrDefaultAsync(x => x.AccountNumber == accountNumber);

    public async Task<IReadOnlyList<AccountChart>> GetByBranchCodeCurrencyCodeAsync(string branchCode, string currencyCode)
        => await Table
            .Where(x => x.BranchCode == branchCode && x.CurrencyCode == currencyCode)
            .ToListAsync();
    public virtual bool IsAccountNumberExist(string acno)
    {
        var accountchart = 
            Table.Where(c => c.AccountNumber.Equals(acno))
            .FirstOrDefault();
        return (accountchart != null);
    }
}
