//// <auto-generated>
//// Generated to match CTH/NCH repository pattern.
//// </auto-generated>

//using Microsoft.Extensions.DependencyInjection;
//using O24OpenAPI.ACT.Domain.AggregatesModel.AccountAggregate;
//using O24OpenAPI.ACT.Domain.AggregatesModel.CommonAggregate;
//using O24OpenAPI.ACT.Domain.AggregatesModel.MappingAggregate;
//using O24OpenAPI.ACT.Domain.AggregatesModel.MiscAggregate;
//using O24OpenAPI.ACT.Domain.AggregatesModel.RulesAggregate;
//using O24OpenAPI.ACT.Domain.AggregatesModel.TransactionAggregate;

//namespace O24OpenAPI.ACT.Infrastructure.Repositories;

///// <summary>
///// Register ACT repositories (CTH/NCH pattern).
///// Call services.AddActRepositories(); inside your ACT.Infrastructure Startup.ConfigureServices.
///// </summary>
//public static class ActRepositoryServiceCollectionExtensions
//{
//    public static IServiceCollection AddActRepositories(this IServiceCollection services)
//    {
//        services.AddScoped<IAccountBalanceRepository, AccountBalanceRepository>();
//        services.AddScoped<IAccountChartRepository, AccountChartRepository>();
//        services.AddScoped<IAccountClearingRepository, AccountClearingRepository>();
//        services.AddScoped<IAccountCommonRepository, AccountCommonRepository>();
//        services.AddScoped<IAccountStatementRepository, AccountStatementRepository>();
//        services.AddScoped<IAccountStatementDoneRepository, AccountStatementDoneRepository>();

//        services.AddScoped<IBranchRepository, BranchRepository>();
//        services.AddScoped<ICurrencyRepository, CurrencyRepository>();

//        services.AddScoped<IAccountMappingRepository, AccountMappingRepository>();
//        services.AddScoped<IAccountMappingDetailRepository, AccountMappingDetailRepository>();

//        services.AddScoped<ISampleDomainRepository, SampleDomainRepository>();

//        services.AddScoped<IAccountingRuleDefinitionRepository, AccountingRuleDefinitionRepository>();
//        services.AddScoped<ICheckingAccountRulesRepository, CheckingAccountRulesRepository>();
//        services.AddScoped<IRuleDefinitionRepository, RuleDefinitionRepository>();
//        services.AddScoped<ITransactionRulesRepository, TransactionRulesRepository>();

//        services.AddScoped<IAccountingTransactionRepository, AccountingTransactionRepository>();
//        services.AddScoped<IForeignExchangeAccountDefinitionRepository, ForeignExchangeAccountDefinitionRepository>();
//        services.AddScoped<IGLEntriesDoneRepository, GLEntriesDoneRepository>();

//        return services;
//    }
//}
