using O24OpenAPI.Generator.Models;
using System.Collections.Generic;
using System.Text;

internal static class WorkflowInvokerEmitter
{
    public static string Emit(IReadOnlyList<WorkflowStepInfo> steps)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using LinKit.Core.Abstractions;");
        sb.AppendLine("using O24OpenAPI.Client.Scheme.Workflow;");
        sb.AppendLine("using O24OpenAPI.Framework.Extensions;");
        sb.AppendLine("using O24OpenAPI.Framework.Abstractions;");
        sb.AppendLine("using LinKit.Core.Cqrs;");
        sb.AppendLine();
        sb.AppendLine("namespace Workflow.Generated");
        sb.AppendLine("{");

        sb.AppendLine("    internal sealed class WorkflowStepInvoker : IWorkflowStepInvoker");
        sb.AppendLine("    {");

        sb.AppendLine(
            "        private readonly Dictionary<string, Func<WFScheme, IMediator, CancellationToken, Task<object>>> _handlers ="
        );
        sb.AppendLine("            new(StringComparer.OrdinalIgnoreCase)");

        if (steps.Count == 0)
        {
            sb.AppendLine("            { };");
        }
        else
        {
            sb.AppendLine("            {");

            foreach (WorkflowStepInfo step in steps)
            {
                sb.AppendLine(
                    $@"
                [""{step.StepCode}""] = static async (scheme, mediator, token) =>
                {{
                    var command =
                        await scheme.ToModel<{step.InputType}>() ?? new {step.InputType}();

                    return await mediator.SendAsync(command, token);
                }},
"
                );
            }

            sb.AppendLine("            };");
        }

        sb.AppendLine();
        sb.AppendLine("        public async Task<object> InvokeAsync(");
        sb.AppendLine("            string stepCode,");
        sb.AppendLine("            WFScheme scheme,");
        sb.AppendLine("            IMediator mediator,");
        sb.AppendLine("            CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_handlers.TryGetValue(stepCode, out var handler))");
        sb.AppendLine("                throw new KeyNotFoundException(");
        sb.AppendLine("                    $\"Workflow step '{stepCode}' handler not found.\");");
        sb.AppendLine();
        sb.AppendLine("            return await handler(scheme, mediator, cancellationToken);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
