namespace O24OpenAPI.Core.Attributes;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GrpcClientAttribute : Attribute
{
    /// <summary>
    /// The type of the gRPC client generated by Grpc.Tools.
    /// E.g., typeof(UserService.UserClient)
    /// </summary>
    public Type GrpcClientType { get; }

    /// <summary>
    /// The name of the RPC method to call on the gRPC client.
    /// E.g., "GetUserAsync"
    /// </summary>
    public string MethodName { get; }

    public GrpcClientAttribute(Type grpcClientType, string methodName)
    {
        GrpcClientType = grpcClientType;
        MethodName = methodName;
    }
}
